/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.civprod.writerstoolbox;

import com.civprod.writerstoolbox.NaturalLanguage.util.TextAndTokenHandling.ChainTextTransformer;
import com.civprod.writerstoolbox.NaturalLanguage.util.TextAndTokenHandling.RegexTokenStripper;
import com.civprod.writerstoolbox.data.html.HTMLTextTransformer;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;

/**
 *
 * @author Steven Owens
 */
public class TagStrippingForm extends javax.swing.JFrame {
    
    public static final Charset UTF_8 = StandardCharsets.UTF_8;

    /**
     * Creates new form StripForm
     */
    public TagStrippingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myFileChooser = new javax.swing.JFileChooser();
        cmdUpdateFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdUpdateFile.setText("update file");
        cmdUpdateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdUpdateFile)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdUpdateFile)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdUpdateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateFileActionPerformed
        final TagStrippingForm tempthis = this;
        new Thread(() -> {
            int returnval = myFileChooser.showOpenDialog(tempthis);
            if (returnval == JFileChooser.APPROVE_OPTION) {
                final File selectedFile = myFileChooser.getSelectedFile();
                final File selectedFileOutput = selectedFile;
                RegexTokenStripper spanStripper = new RegexTokenStripper("<span[^>]*>","</span>");
                HTMLTextTransformer myHTMLTextTransformer = new HTMLTextTransformer();
                ChainTextTransformer myChainTextTransformer = new ChainTextTransformer(spanStripper,myHTMLTextTransformer);
                java.io.BufferedReader fin = null;
                String FileData = "";
                try {
                    fin = new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(selectedFile),UTF_8));
                    FileData = fin.lines().collect(Collectors.joining("\n"));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TagStrippingForm.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    if (fin != null){
                        try {
                            fin.close();
                        } catch (IOException ex) {
                            Logger.getLogger(TagStrippingForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                FileData = myChainTextTransformer.transform(FileData);
                java.io.BufferedWriter fout = null;
                try {
                    fout = new java.io.BufferedWriter(new java.io.OutputStreamWriter(new java.io.FileOutputStream(selectedFileOutput),UTF_8));
                    fout.append(FileData);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TagStrippingForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TagStrippingForm.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    if (fout != null){
                        try {
                            fout.close();
                        } catch (IOException ex) {
                            Logger.getLogger(TagStrippingForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                
            }
        }).start();
    }//GEN-LAST:event_cmdUpdateFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TagStrippingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TagStrippingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TagStrippingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TagStrippingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TagStrippingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdUpdateFile;
    private javax.swing.JFileChooser myFileChooser;
    // End of variables declaration//GEN-END:variables
}
